# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AerospaceUtils < Formula
  desc "CLI for managing Aerospace workspace sizing based on monitor gaps"
  homepage "https://github.com/mholtzscher/aerospace-utils"
  version "0.3.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/mholtzscher/aerospace-utils/releases/download/v0.3.4/aerospace-utils_0.3.4_darwin_arm64.tar.gz"
    sha256 "df5893da67367afa14ed24d1e3b7e919dd3c61aa74372c3dee5e17dd32a5dc7f"

    define_method(:install) do
      bin.install "aerospace-utils"
    end
  end

  test do
    system "#{bin}/aerospace-utils", "--version"
  end
end
