# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Agent first CLI for Atlassian products"
  homepage "https://github.com/mholtzscher/atlas"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.1/atlas_0.1.1_darwin_amd64.tar.gz"
      sha256 "65939f5b438f73e48d0b3c2cc3c08bad6be9f8face069507214834aa79538ed6"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.1/atlas_0.1.1_darwin_arm64.tar.gz"
      sha256 "8c28f9d03a2847c922119813321b8113e70ab8554ffd9041a5a614236e28535c"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.1/atlas_0.1.1_linux_amd64.tar.gz"
      sha256 "9cbb731deb4b259b34a3293eece5cebd7f0bbef215a4063d4d980eb4276723e6"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.1/atlas_0.1.1_linux_arm64.tar.gz"
      sha256 "53321d63d8b5ce37a447e0a1b6f206e6c160024e75ac325a37185efcd778fe54"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "--version"
  end
end
