# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlas < Formula
  desc "Agent first CLI for Atlassian products"
  homepage "https://github.com/mholtzscher/atlas"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_amd64.tar.gz"
      sha256 "7a702faff23dd7dbeab4e31dbe8d61a9c85a7d29677369ce5e07c00c5a94d925"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.0/atlas_0.1.0_darwin_arm64.tar.gz"
      sha256 "e969a66cb18e9f9dc58d9ff84ed292d9a03e1916ad52d4088c3f307f0b14d45c"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_amd64.tar.gz"
      sha256 "bd7f21505cc2f79f8167069d4557fbf8f8edbfffea326721fbcbf105ef979eab"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/atlas/releases/download/v0.1.0/atlas_0.1.0_linux_arm64.tar.gz"
      sha256 "738d95fdae5e0efd3066877b034fcd5b9f71fdcc5ec25188107027d2141cac93"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "--version"
  end
end
