# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubJanitor < Formula
  desc "Synchronize GitHub repository settings across multiple repos"
  homepage "https://github.com/mholtzscher/github-janitor"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.0/github-janitor_0.1.0_darwin_arm64.tar.gz"
      sha256 :no_check

      def install
        bin.install "github-janitor"
      end
    end
    on_intel do
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.0/github-janitor_0.1.0_darwin_amd64.tar.gz"
      sha256 :no_check

      def install
        bin.install "github-janitor"
      end
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.0/github-janitor_0.1.0_linux_arm64.tar.gz"
      sha256 :no_check

      def install
        bin.install "github-janitor"
      end
    end
    on_intel do
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.0/github-janitor_0.1.0_linux_amd64.tar.gz"
      sha256 :no_check

      def install
        bin.install "github-janitor"
      end
    end
  end

  test do
    system "#{bin}/github-janitor", "--version"
  end
end
