# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubJanitor < Formula
  desc "A Go CLI tool built with Nix"
  homepage "https://github.com/mholtzscher/github-janitor"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.2/github-janitor_0.1.2_darwin_amd64.tar.gz"
      sha256 "ec87706b8c058476ac9a490f4f5640d84ab81685ca0054281f3d2ba75f60ebc9"

      def install
        bin.install "github-janitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.2/github-janitor_0.1.2_darwin_arm64.tar.gz"
      sha256 "0ed8f26a5597d51efde21046b39bcedf6c63046ba6f7153bf1effcf25c8edd79"

      def install
        bin.install "github-janitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.2/github-janitor_0.1.2_linux_amd64.tar.gz"
      sha256 "d0dadfd0dc78890c0cc5478a8ea9ba3e8e47ed3b74bfaf2567882529205553df"
      def install
        bin.install "github-janitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/github-janitor/releases/download/v0.1.2/github-janitor_0.1.2_linux_arm64.tar.gz"
      sha256 "3c8039d61af9092c20a3445668fae0ad93f1a9c800d2217c4c3b19050809bd7e"
      def install
        bin.install "github-janitor"
      end
    end
  end

  test do
    system "#{bin}/github-janitor", "--version"
  end
end
