# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "A Go CLI tool built with Nix"
  homepage "https://github.com/mholtzscher/today"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.3/today_0.1.3_darwin_amd64.tar.gz"
      sha256 "ac13bbcc06b9c436c6dfba5f63543faf8f55475db650efcfa454868f5bcffd88"

      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.3/today_0.1.3_darwin_arm64.tar.gz"
      sha256 "029f22d33c41f53754217cb0e017371e7aa39a2bbae22e0aa19876b785fd22bb"

      def install
        bin.install "today"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.3/today_0.1.3_linux_amd64.tar.gz"
      sha256 "f6e27848b7645f0961e21f117e96b9fb10d1422c79d0c1d97d5418b56e8aaa67"
      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.3/today_0.1.3_linux_arm64.tar.gz"
      sha256 "9c8e191e0a7bb9edec0af2f14f8a54ed2798f39934e3b0e057fedaa94db3a19a"
      def install
        bin.install "today"
      end
    end
  end

  test do
    system "#{bin}/today", "--version"
  end
end
