# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "A Go CLI tool built with Nix"
  homepage "https://github.com/mholtzscher/today"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.5/today_0.1.5_darwin_amd64.tar.gz"
      sha256 "2cdc8c90e700a21a589d1822efab0360719f323c0f298cb4b829848fa8d9f345"

      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.5/today_0.1.5_darwin_arm64.tar.gz"
      sha256 "f5613be35db360a81008d80d26ece410f2f40c8183231a34384da1b6624e46a2"

      def install
        bin.install "today"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.5/today_0.1.5_linux_amd64.tar.gz"
      sha256 "176eaac39f3069a903455d594465f93f68fb0f23c36c2ad11198af1586937821"
      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.5/today_0.1.5_linux_arm64.tar.gz"
      sha256 "772a73d15e745ad0b8130e5ca59c63ece23528e8a55d49905958676703d2230d"
      def install
        bin.install "today"
      end
    end
  end

  test do
    system "#{bin}/today", "--version"
  end
end
