# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Today < Formula
  desc "A Go CLI tool built with Nix"
  homepage "https://github.com/mholtzscher/today"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.4/today_0.1.4_darwin_amd64.tar.gz"
      sha256 "c6f6c896a726e4bda41452e1d570c7a04c16584a8a4e64308b04806470cd8f66"

      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.4/today_0.1.4_darwin_arm64.tar.gz"
      sha256 "543613cee465ab3c0d3d5a54bd9caafecbf4ec8fa981c4f8910115be46f5873b"

      def install
        bin.install "today"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.4/today_0.1.4_linux_amd64.tar.gz"
      sha256 "87ce1f98aaaa0bdd6a07b5d91e0f95660718c106f2bf884ef283cb00083b9e2b"
      def install
        bin.install "today"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/today/releases/download/v0.1.4/today_0.1.4_linux_arm64.tar.gz"
      sha256 "7a198a3ce47cf1796253a285d0d8967ae25383082a8c8056a5627154006f02fb"
      def install
        bin.install "today"
      end
    end
  end

  test do
    system "#{bin}/today", "--version"
  end
end
