# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ugh < Formula
  desc "A todo.txt-inspired task CLI with SQLite storage."
  homepage "https://github.com/mholtzscher/ugh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mholtzscher/ugh/releases/download/v0.1.3/ugh_0.1.3_darwin_amd64.tar.gz"
      sha256 "63d008e7ddcf90886891666d48d3a36614eddf5603cf9379333027f3693537cd"

      def install
        bin.install "ugh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mholtzscher/ugh/releases/download/v0.1.3/ugh_0.1.3_darwin_arm64.tar.gz"
      sha256 "6eb3f36ed601be9ab8e5a2c839332a73efb871ba0eb3514374d332bff46a9150"

      def install
        bin.install "ugh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/ugh/releases/download/v0.1.3/ugh_0.1.3_linux_amd64.tar.gz"
      sha256 "934ad372276c4640f1743b524f10576fd9b084f7c7f11e97eb2b53b5cc2f1248"
      def install
        bin.install "ugh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mholtzscher/ugh/releases/download/v0.1.3/ugh_0.1.3_linux_arm64.tar.gz"
      sha256 "70e87d70636e581b4d6f8222b565c4bb52475f3d6f78b8708a4c74818cb7b0f6"
      def install
        bin.install "ugh"
      end
    end
  end

  test do
    system "#{bin}/ugh", "--version"
  end
end
